#!/usr/bin/env bash

# Performing database migration
flask db upgrade

# Adding a API user
flask adduser $APP_DEFAULT_USERNAME $APP_DEFAULT_PASS

# Running the Flask application
if [ "$FLASK_ENV" = "development" ] || [ "$FLASK_ENV" = "testing" ]
then
  python -m flask run --host=0.0.0.0 --port=$FLASK_PORT  
else
  waitress-serve --port=$FLASK_PORT --call 'app:create_app' 
fi
