"""empty message

Revision ID: 252192babab4
Revises: 3e13f1767019
Create Date: 2021-05-04 20:21:43.068712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252192babab4'
down_revision = '3e13f1767019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exame_order',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.drop_constraint('exam_order_id_fkey', 'exam', type_='foreignkey')
    op.drop_column('exam', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exam_order_id_fkey', 'exam', 'order', ['order_id'], ['id'])
    op.drop_table('exame_order')
    # ### end Alembic commands ###
