"""empty message

Revision ID: 32b0462231b0
Revises: 675b889d0548
Create Date: 2021-05-05 03:32:01.918266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b0462231b0'
down_revision = '675b889d0548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('physician_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'physician', ['physician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'physician_id')
    # ### end Alembic commands ###
