"""empty message

Revision ID: 3e13f1767019
Revises: 41fdaa0fa35a
Create Date: 2021-05-04 19:38:19.944259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e13f1767019'
down_revision = '41fdaa0fa35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exame_order')
    op.add_column('exam', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_column('exam', 'order_id')
    op.create_table('exame_order',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='exame_order_exam_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='exame_order_order_id_fkey')
    )
    # ### end Alembic commands ###
