"""empty message

Revision ID: 5889234f2c7d
Revises: 252192babab4
Create Date: 2021-05-04 22:38:32.141358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5889234f2c7d'
down_revision = '252192babab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physician_exame',
    sa.Column('physician_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.id'], )
    )
    op.drop_constraint('exam_physician_id_fkey', 'exam', type_='foreignkey')
    op.drop_column('exam', 'physician_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('physician_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exam_physician_id_fkey', 'exam', 'physician', ['physician_id'], ['id'])
    op.drop_table('physician_exame')
    # ### end Alembic commands ###
