"""empty message

Revision ID: 675b889d0548
Revises: 5889234f2c7d
Create Date: 2021-05-05 02:29:09.400558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675b889d0548'
down_revision = '5889234f2c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('patient', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'weight')
    op.drop_column('patient', 'height')
    # ### end Alembic commands ###
