"""empty message

Revision ID: e90ad196e02c
Revises: ca6d59cbb0c1
Create Date: 2021-04-29 20:00:19.074773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90ad196e02c'
down_revision = 'ca6d59cbb0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physician_exame',
    sa.Column('physician_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.id'], )
    )
    op.create_table('exame_order',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.add_column('order', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'patient_id')
    op.drop_table('exame_order')
    op.drop_table('physician_exame')
    # ### end Alembic commands ###
